djangoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myapp.urls")),
]

myapp/urls.py
from . import views
from django.urls import path

app_name = "myapp"
urlpatterns = [
    path("", views.redirect_to_index, name="index"),
    path("index/", views.NoteIndexView.as_view(), name="index"),
    path("myapp/create/", views.NoteCreateView.as_view(), name="note_input"),
    path("myapp/detail/<uuid:pk>/",
         views.NoteDetailView.as_view(), name="note_detail"),
    path("myapp/update/<uuid:pk>/",
         views.NoteUpdateView.as_view(), name="note_update"),
    path("myapp/delete/<uuid:pk>/",
         views.NoteDeleteView.as_view(), name="note_delete"),
]

myapp/models.py
import uuid
from django.db import models
from django.utils import timezone


# Create your models here.
class NoteTable(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(verbose_name="見出し", max_length=100)
    text = models.TextField(verbose_name="本文", max_length=400)
    created_at = models.DateTimeField(verbose_name="作成日付", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="編集日付", blank=True, null=True)

myapp/forms.py
from django import forms
from .models import NoteTable


class NoteForm(forms.ModelForm):
    class Meta:
        model = NoteTable
        fields = ("title", "text")

myapp/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from .forms import NoteForm
from .models import NoteTable
from django.utils import timezone
from django.shortcuts import redirect
from django.contrib import messages

# Create your views here.


def redirect_to_index(request):
    return redirect("myapp:index")


class NoteIndexView(ListView):
    template_name = "index.html"
    model = NoteTable
    ordering = "-updated_at"


class NoteCreateView(CreateView):
    template_name = "note_input.html"
    form_class = NoteForm
    success_url = reverse_lazy("myapp:index")

    def form_valid(self, form):
        note = form.save(commit=False)
        note.updated_at = timezone.now()
        note.save()
        messages.success(self.request, "sucessful: 作成しました。")
        return super().form_valid(form)


class NoteDetailView(DetailView):
    template_name = "note_detail.html"
    model = NoteTable


class NoteUpdateView(UpdateView):
    template_name = "note_update.html"
    model = NoteTable
    fields = ("title", "text")
    success_url = reverse_lazy("myapp:index")

    def form_valid(self, form):
        note = form.save(commit=False)
        note.updated_at = timezone.now()
        note.save()
        messages.success(self.request, "sucessful: 更新しました。")
        return super().form_valid(form)


class NoteDeleteView(DeleteView):
    template_name = "note_delete.html"
    model = NoteTable
    success_url = reverse_lazy("myapp:index")

    def delete(self, request, *args, **kwargs):
        messages.warning(self.request, "warn: 削除しました。")
        return super().delete(request, *args, **kwargs)

templates/header.html
{% load static %}

<head>
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,1,0" />
    <link
        href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400;500;700;800;900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/header_style.css' %}">
</head>

<body>
    <p class="icon"><span class="material-symbols-rounded">edit_square</span>メモ帳</p>
    <ul>
        <li>
            <a href="{% url 'myapp:index' %}"><span class="material-symbols-rounded">home</span>ホーム</a>
        </li>
        <li>
            <a href="{% url 'myapp:note_input' %}"><span class="material-symbols-rounded">add</span>新規メモ</a>
        </li>
    </ul>
</body>

templates/index.html
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/general_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/list_style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <title>メモ帳 | トップ</title>
</head>

<body>
    {% for message in messages %}
    <div {% if message.tags %}class="{{ message.tags }}" {% endif %}>
        {{ message }}
    </div>
    {% endfor %}
    <div class="main-contents">
        <header>
            {% include 'header.html' %}
        </header>
        <main>
            <div class="section-title">
                <h1>メモ一覧</h1>
            </div>
            <div class="list main-section">
                {% for note in object_list %}
                <a href="{% url 'myapp:note_detail' note.pk %}" class="text-decoration-none">
                    <div class="content">
                        <h3 class="title">{{ note.title }}</h3>
                        <p class="text">{{ note.text }}</p>
                        <p class="date">{{ note.created_at | date:"Y年m月d日" }}</p>
                    </div>
                </a>
                {% endfor %}
            </div>
        </main>
        <script src="{% static 'js/index.js' %}"></script>
    </div>
</body>

</html>

templates/note_delete.html
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/general_style.css' %}">
    <title>メモ帳 | 削除確認</title>
</head>

<body>
    <div class="main-contents">
        <header>
            {% include 'header.html' %}
        </header>
        <main>
            <div class="section-title">
                <h1>メモの削除</h1>
            </div>
            <div class="main-section">
                <form method="post">
                    {% csrf_token %}
                    <p>{{ object.created_at }} {{ object.title }} を削除します</p>
                    {% bootstrap_button button_type="submit" content="削除確定" size="md" %}
                </form>
            </div>
        </main>
        <script src="{% static 'js/index.js' %}"></script>
    </div>
</body>

</html>

templates/note_detail.html
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/general_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/detail_style.css' %}">
    <title>メモ帳 | 詳細</title>
</head>

<body>
    <div class="main-contents">
        <header>
            {% include 'header.html' %}
        </header>
        <main>
            <div class="section-title">
                <h1>{{ object.title }}</h1>
            </div>
            <div class="main-section">
                <p class="body">{{ object.text }}</p>
                <div class="dates">
                    <p>作成日時: {{ object.created_at }}</p>
                    <p>最終更新: {{ object.updated_at }}</p>
                </div>
                <div class="control">
                    <a href="{% url 'myapp:note_update' object.pk %}"><span class="material-symbols-rounded">
                            edit_square
                        </span>編集</a>
                    <a href="{% url 'myapp:note_delete' object.pk%}"><span class="material-symbols-rounded">
                            delete
                        </span>削除</a>
                </div>
            </div>
        </main>
        <script src="{% static 'js/index.js' %}"></script>
    </div>
</body>

</html>

templates/note_input.html
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/general_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/input_style.css' %}">
    <title>メモ帳 | 新規メモ</title>
</head>

<body>
    <div class="main-contents">
        <header>
            {% include 'header.html' %}
        </header>
        <main>
            <div class="section-title">
                <h1>新規メモ</h1>
            </div>
            <form method="post" class="main-section">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="新規追加" size="md" %}
            </form>
        </main>
        <script src="{% static 'js/index.js' %}"></script>
    </div>
</body>

</html>

templates/note_update.html
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/general_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/input_style.css' %}">
    <title>メモ帳 | 編集</title>
</head>

<body>
    <div class="main-contents">
        <header>
            {% include 'header.html' %}
        </header>
        <main>
            <div class="section-title">
                <h1>メモの編集</h1>
            </div>
            <form method="post" class="main-section">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="保存" size="md" %}
            </form>
        </main>
        <script src="{% static 'js/index.js' %}"></script>
    </div>
</body>

</html>